name: Bump package version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'A valid semver string, a valid second argument to semver.inc (one of patch, minor, major, prepatch, preminor, premajor, prerelease), or from-git.'
        required: true
        default: 'minor'
      preid:
        description: 'A valid semver pre-release id (such as alpha, beta, rc, etc.).'
        required: false
        default: ''

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - name: Config author
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Bump version
        run: npm version ${{github.event.inputs.version}} --preid=${{github.event.inputs.preid}}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Push changes and tag
        run: git push --follow-tags
